# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('max_people_num', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('place', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('pic_url', models.CharField(max_length=256)),
                ('homepage_url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_type', models.IntegerField()),
                ('account_name', models.CharField(max_length=128, unique=True)),
                ('account_password', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('email_address', models.CharField(max_length=128)),
                ('phone_num', models.IntegerField()),
                ('pic_url', models.CharField(max_length=128)),
                ('homepage_url', models.CharField(max_length=128)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('registered_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_type', models.IntegerField(default=2)),
                ('account_name', models.CharField(max_length=128, unique=True)),
                ('account_password', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
                ('email_address', models.CharField(default='', max_length=128)),
                ('phone_num', models.IntegerField(default=0)),
                ('pic_url', models.CharField(default='', max_length=128)),
                ('user_name', models.CharField(default='', max_length=64)),
                ('user_IDnum', models.IntegerField(unique=True)),
                ('registered_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Organizer'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Meeting'),
        ),
    ]
