# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20161207_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='max_people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='phone_num',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_num',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pic_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_IDnum',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.MyUser'),
        ),
    ]
