# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20161207_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='open_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
