# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20161207_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
