# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-11 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20161211_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='homepage_url',
        ),
    ]
