# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20161212_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='homepage_url',
        ),
        migrations.AddField(
            model_name='myuser',
            name='name_true',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
