# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20161213_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
