# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
