# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0012_auto_20161219_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='fromname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
