# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0013_auto_20161220_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='open_id',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
